[SERVICE]
    # バッファフラッシュ間隔 (秒)
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Tag          simulator
    Path         /var/log/bosonic-simulator/server.log
    read_from_head   true
    Refresh_Interval 5

[OUTPUT]
    Name        stdout
    Match       *

[OUTPUT]
    Name        file
    Path        /var/log/fluent-bit
    File        simulator-server.log
    Match       *
    Mkdir       On

[OUTPUT]
    Name                cloudwatch_logs
    Match               *
    log_group_name      ${LOG_GROUP_NAME}
    log_stream_prefix   simulator_log
    log_key             log
    retry_limit         1
    region              ${AWS_REGION}
    role_arn            ${ROLE_ARN}

[OUTPUT]
    Name    s3
    Match   *
    bucket  ${S3_BUCKET_NAME}
    total_file_size  5M
    upload_timeout   1m
    use_put_object  On
    compression gzip
    s3_key_format                /$TAG/%Y/%m/%d/%H_%M_%S.gz
    region              ${AWS_REGION}
    role_arn            ${ROLE_ARN}
