// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/common/v1/error_detail.proto
// Protobuf C++ Version: 5.28.3

#include "mqc3_cloud/common/v1/error_detail.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mqc3_cloud {
namespace common {
namespace v1 {

inline constexpr ErrorDetail::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        description_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ErrorDetail::ErrorDetail(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ErrorDetailDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorDetailDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorDetailDefaultTypeInternal() {}
  union {
    ErrorDetail _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorDetailDefaultTypeInternal _ErrorDetail_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto = nullptr;
const ::uint32_t
    TableStruct_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::ErrorDetail, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::ErrorDetail, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::ErrorDetail, _impl_.description_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::mqc3_cloud::common::v1::ErrorDetail)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::mqc3_cloud::common::v1::_ErrorDetail_default_instance_._instance,
};
const char descriptor_table_protodef_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\'mqc3_cloud/common/v1/error_detail.prot"
    "o\022\024mqc3_cloud.common.v1\"C\n\013ErrorDetail\022\022"
    "\n\004code\030\001 \001(\tR\004code\022 \n\013description\030\002 \001(\tR"
    "\013descriptionB\232\001\n\030com.mqc3_cloud.common.v"
    "1B\020ErrorDetailProtoP\001\242\002\003MCX\252\002\023Mqc3Cloud."
    "Common.V1\312\002\023Mqc3Cloud\\Common\\V1\342\002\037Mqc3Cl"
    "oud\\Common\\V1\\GPBMetadata\352\002\025Mqc3Cloud::C"
    "ommon::V1b\006proto3"
};
static ::absl::once_flag descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto = {
    false,
    false,
    297,
    descriptor_table_protodef_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto,
    "mqc3_cloud/common/v1/error_detail.proto",
    &descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto::offsets,
    file_level_enum_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto,
    file_level_service_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto,
};
namespace mqc3_cloud {
namespace common {
namespace v1 {
// ===================================================================

class ErrorDetail::_Internal {
 public:
};

ErrorDetail::ErrorDetail(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mqc3_cloud.common.v1.ErrorDetail)
}
inline PROTOBUF_NDEBUG_INLINE ErrorDetail::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mqc3_cloud::common::v1::ErrorDetail& from_msg)
      : code_(arena, from.code_),
        description_(arena, from.description_),
        _cached_size_{0} {}

ErrorDetail::ErrorDetail(
    ::google::protobuf::Arena* arena,
    const ErrorDetail& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ErrorDetail* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:mqc3_cloud.common.v1.ErrorDetail)
}
inline PROTOBUF_NDEBUG_INLINE ErrorDetail::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : code_(arena),
        description_(arena),
        _cached_size_{0} {}

inline void ErrorDetail::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ErrorDetail::~ErrorDetail() {
  // @@protoc_insertion_point(destructor:mqc3_cloud.common.v1.ErrorDetail)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ErrorDetail::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.code_.Destroy();
  _impl_.description_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ErrorDetail::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ErrorDetail_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ErrorDetail::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ErrorDetail>(),
            ::google::protobuf::Message::GetNewImpl<ErrorDetail>(),
            ::google::protobuf::Message::GetClearImpl<ErrorDetail>(), &ErrorDetail::ByteSizeLong,
                &ErrorDetail::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ErrorDetail, _impl_._cached_size_),
            false,
        },
        &ErrorDetail::kDescriptorMethods,
        &descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ErrorDetail::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 56, 2> ErrorDetail::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mqc3_cloud::common::v1::ErrorDetail>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string description = 2 [json_name = "description"];
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ErrorDetail, _impl_.description_)}},
    // string code = 1 [json_name = "code"];
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ErrorDetail, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string code = 1 [json_name = "code"];
    {PROTOBUF_FIELD_OFFSET(ErrorDetail, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string description = 2 [json_name = "description"];
    {PROTOBUF_FIELD_OFFSET(ErrorDetail, _impl_.description_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\4\13\0\0\0\0\0"
    "mqc3_cloud.common.v1.ErrorDetail"
    "code"
    "description"
  }},
};

PROTOBUF_NOINLINE void ErrorDetail::Clear() {
// @@protoc_insertion_point(message_clear_start:mqc3_cloud.common.v1.ErrorDetail)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.ClearToEmpty();
  _impl_.description_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ErrorDetail::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ErrorDetail& this_ = static_cast<const ErrorDetail&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ErrorDetail::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ErrorDetail& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mqc3_cloud.common.v1.ErrorDetail)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string code = 1 [json_name = "code"];
          if (!this_._internal_code().empty()) {
            const std::string& _s = this_._internal_code();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mqc3_cloud.common.v1.ErrorDetail.code");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string description = 2 [json_name = "description"];
          if (!this_._internal_description().empty()) {
            const std::string& _s = this_._internal_description();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mqc3_cloud.common.v1.ErrorDetail.description");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mqc3_cloud.common.v1.ErrorDetail)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ErrorDetail::ByteSizeLong(const MessageLite& base) {
          const ErrorDetail& this_ = static_cast<const ErrorDetail&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ErrorDetail::ByteSizeLong() const {
          const ErrorDetail& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mqc3_cloud.common.v1.ErrorDetail)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string code = 1 [json_name = "code"];
            if (!this_._internal_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_code());
            }
            // string description = 2 [json_name = "description"];
            if (!this_._internal_description().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_description());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ErrorDetail::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ErrorDetail*>(&to_msg);
  auto& from = static_cast<const ErrorDetail&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mqc3_cloud.common.v1.ErrorDetail)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (!from._internal_description().empty()) {
    _this->_internal_set_description(from._internal_description());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorDetail::CopyFrom(const ErrorDetail& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqc3_cloud.common.v1.ErrorDetail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ErrorDetail::InternalSwap(ErrorDetail* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.code_, &other->_impl_.code_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.description_, &other->_impl_.description_, arena);
}

::google::protobuf::Metadata ErrorDetail::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ferror_5fdetail_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
