// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/common/v1/function.proto
// Protobuf C++ Version: 5.28.3

#include "mqc3_cloud/common/v1/function.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mqc3_cloud {
namespace common {
namespace v1 {

inline constexpr PythonFunction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : code_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PythonFunction::PythonFunction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PythonFunctionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PythonFunctionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PythonFunctionDefaultTypeInternal() {}
  union {
    PythonFunction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PythonFunctionDefaultTypeInternal _PythonFunction_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto = nullptr;
const ::uint32_t
    TableStruct_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::PythonFunction, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::PythonFunction, _impl_.code_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::mqc3_cloud::common::v1::PythonFunction)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::mqc3_cloud::common::v1::_PythonFunction_default_instance_._instance,
};
const char descriptor_table_protodef_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#mqc3_cloud/common/v1/function.proto\022\024m"
    "qc3_cloud.common.v1\"$\n\016PythonFunction\022\022\n"
    "\004code\030\002 \003(\tR\004codeB\227\001\n\030com.mqc3_cloud.com"
    "mon.v1B\rFunctionProtoP\001\242\002\003MCX\252\002\023Mqc3Clou"
    "d.Common.V1\312\002\023Mqc3Cloud\\Common\\V1\342\002\037Mqc3"
    "Cloud\\Common\\V1\\GPBMetadata\352\002\025Mqc3Cloud:"
    ":Common::V1b\006proto3"
};
static ::absl::once_flag descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto = {
    false,
    false,
    259,
    descriptor_table_protodef_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto,
    "mqc3_cloud/common/v1/function.proto",
    &descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto::offsets,
    file_level_enum_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto,
    file_level_service_descriptors_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto,
};
namespace mqc3_cloud {
namespace common {
namespace v1 {
// ===================================================================

class PythonFunction::_Internal {
 public:
};

PythonFunction::PythonFunction(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mqc3_cloud.common.v1.PythonFunction)
}
inline PROTOBUF_NDEBUG_INLINE PythonFunction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mqc3_cloud::common::v1::PythonFunction& from_msg)
      : code_{visibility, arena, from.code_},
        _cached_size_{0} {}

PythonFunction::PythonFunction(
    ::google::protobuf::Arena* arena,
    const PythonFunction& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PythonFunction* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:mqc3_cloud.common.v1.PythonFunction)
}
inline PROTOBUF_NDEBUG_INLINE PythonFunction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : code_{visibility, arena},
        _cached_size_{0} {}

inline void PythonFunction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PythonFunction::~PythonFunction() {
  // @@protoc_insertion_point(destructor:mqc3_cloud.common.v1.PythonFunction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PythonFunction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    PythonFunction::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_PythonFunction_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &PythonFunction::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<PythonFunction>(),
            ::google::protobuf::Message::GetNewImpl<PythonFunction>(),
            ::google::protobuf::Message::GetClearImpl<PythonFunction>(), &PythonFunction::ByteSizeLong,
                &PythonFunction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(PythonFunction, _impl_._cached_size_),
            false,
        },
        &PythonFunction::kDescriptorMethods,
        &descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* PythonFunction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 48, 2> PythonFunction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mqc3_cloud::common::v1::PythonFunction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string code = 2 [json_name = "code"];
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PythonFunction, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string code = 2 [json_name = "code"];
    {PROTOBUF_FIELD_OFFSET(PythonFunction, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\43\4\0\0\0\0\0\0"
    "mqc3_cloud.common.v1.PythonFunction"
    "code"
  }},
};

PROTOBUF_NOINLINE void PythonFunction::Clear() {
// @@protoc_insertion_point(message_clear_start:mqc3_cloud.common.v1.PythonFunction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PythonFunction::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PythonFunction& this_ = static_cast<const PythonFunction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PythonFunction::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PythonFunction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mqc3_cloud.common.v1.PythonFunction)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string code = 2 [json_name = "code"];
          for (int i = 0, n = this_._internal_code_size(); i < n; ++i) {
            const auto& s = this_._internal_code().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mqc3_cloud.common.v1.PythonFunction.code");
            target = stream->WriteString(2, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mqc3_cloud.common.v1.PythonFunction)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PythonFunction::ByteSizeLong(const MessageLite& base) {
          const PythonFunction& this_ = static_cast<const PythonFunction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PythonFunction::ByteSizeLong() const {
          const PythonFunction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mqc3_cloud.common.v1.PythonFunction)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string code = 2 [json_name = "code"];
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_code().size());
              for (int i = 0, n = this_._internal_code().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_code().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PythonFunction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PythonFunction*>(&to_msg);
  auto& from = static_cast<const PythonFunction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mqc3_cloud.common.v1.PythonFunction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_code()->MergeFrom(from._internal_code());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PythonFunction::CopyFrom(const PythonFunction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqc3_cloud.common.v1.PythonFunction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PythonFunction::InternalSwap(PythonFunction* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.code_.InternalSwap(&other->_impl_.code_);
}

::google::protobuf::Metadata PythonFunction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
