// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/common/v1/function.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto;
namespace mqc3_cloud {
namespace common {
namespace v1 {
class PythonFunction;
struct PythonFunctionDefaultTypeInternal;
extern PythonFunctionDefaultTypeInternal _PythonFunction_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mqc3_cloud {
namespace common {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class PythonFunction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqc3_cloud.common.v1.PythonFunction) */ {
 public:
  inline PythonFunction() : PythonFunction(nullptr) {}
  ~PythonFunction() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PythonFunction(
      ::google::protobuf::internal::ConstantInitialized);

  inline PythonFunction(const PythonFunction& from) : PythonFunction(nullptr, from) {}
  inline PythonFunction(PythonFunction&& from) noexcept
      : PythonFunction(nullptr, std::move(from)) {}
  inline PythonFunction& operator=(const PythonFunction& from) {
    CopyFrom(from);
    return *this;
  }
  inline PythonFunction& operator=(PythonFunction&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PythonFunction& default_instance() {
    return *internal_default_instance();
  }
  static inline const PythonFunction* internal_default_instance() {
    return reinterpret_cast<const PythonFunction*>(
        &_PythonFunction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PythonFunction& a, PythonFunction& b) { a.Swap(&b); }
  inline void Swap(PythonFunction* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PythonFunction* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PythonFunction* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<PythonFunction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PythonFunction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PythonFunction& from) { PythonFunction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PythonFunction* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mqc3_cloud.common.v1.PythonFunction"; }

 protected:
  explicit PythonFunction(::google::protobuf::Arena* arena);
  PythonFunction(::google::protobuf::Arena* arena, const PythonFunction& from);
  PythonFunction(::google::protobuf::Arena* arena, PythonFunction&& from) noexcept
      : PythonFunction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCodeFieldNumber = 2,
  };
  // repeated string code = 2 [json_name = "code"];
  int code_size() const;
  private:
  int _internal_code_size() const;

  public:
  void clear_code() ;
  const std::string& code(int index) const;
  std::string* mutable_code(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_code(int index, Arg_&& value, Args_... args);
  std::string* add_code();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_code(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& code() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_code();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_code() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_code();

  public:
  // @@protoc_insertion_point(class_scope:mqc3_cloud.common.v1.PythonFunction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      48, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_PythonFunction_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PythonFunction& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> code_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PythonFunction

// repeated string code = 2 [json_name = "code"];
inline int PythonFunction::_internal_code_size() const {
  return _internal_code().size();
}
inline int PythonFunction::code_size() const {
  return _internal_code_size();
}
inline void PythonFunction::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.Clear();
}
inline std::string* PythonFunction::add_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_code()->Add();
  // @@protoc_insertion_point(field_add_mutable:mqc3_cloud.common.v1.PythonFunction.code)
  return _s;
}
inline const std::string& PythonFunction::code(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.common.v1.PythonFunction.code)
  return _internal_code().Get(index);
}
inline std::string* PythonFunction::mutable_code(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.common.v1.PythonFunction.code)
  return _internal_mutable_code()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void PythonFunction::set_code(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_code()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:mqc3_cloud.common.v1.PythonFunction.code)
}
template <typename Arg_, typename... Args_>
inline void PythonFunction::add_code(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_code(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:mqc3_cloud.common.v1.PythonFunction.code)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
PythonFunction::code() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mqc3_cloud.common.v1.PythonFunction.code)
  return _internal_code();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
PythonFunction::mutable_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:mqc3_cloud.common.v1.PythonFunction.code)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_code();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
PythonFunction::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
PythonFunction::_internal_mutable_code() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.code_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fcommon_2fv1_2ffunction_2eproto_2epb_2eh
