// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/common/v1/math.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto;
namespace mqc3_cloud {
namespace common {
namespace v1 {
class Complex;
struct ComplexDefaultTypeInternal;
extern ComplexDefaultTypeInternal _Complex_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mqc3_cloud {
namespace common {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class Complex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqc3_cloud.common.v1.Complex) */ {
 public:
  inline Complex() : Complex(nullptr) {}
  ~Complex() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Complex(
      ::google::protobuf::internal::ConstantInitialized);

  inline Complex(const Complex& from) : Complex(nullptr, from) {}
  inline Complex(Complex&& from) noexcept
      : Complex(nullptr, std::move(from)) {}
  inline Complex& operator=(const Complex& from) {
    CopyFrom(from);
    return *this;
  }
  inline Complex& operator=(Complex&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Complex& default_instance() {
    return *internal_default_instance();
  }
  static inline const Complex* internal_default_instance() {
    return reinterpret_cast<const Complex*>(
        &_Complex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Complex& a, Complex& b) { a.Swap(&b); }
  inline void Swap(Complex* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Complex* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Complex* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Complex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Complex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Complex& from) { Complex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Complex* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mqc3_cloud.common.v1.Complex"; }

 protected:
  explicit Complex(::google::protobuf::Arena* arena);
  Complex(::google::protobuf::Arena* arena, const Complex& from);
  Complex(::google::protobuf::Arena* arena, Complex&& from) noexcept
      : Complex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRealFieldNumber = 1,
    kImagFieldNumber = 2,
  };
  // float real = 1 [json_name = "real"];
  void clear_real() ;
  float real() const;
  void set_real(float value);

  private:
  float _internal_real() const;
  void _internal_set_real(float value);

  public:
  // float imag = 2 [json_name = "imag"];
  void clear_imag() ;
  float imag() const;
  void set_imag(float value);

  private:
  float _internal_imag() const;
  void _internal_set_imag(float value);

  public:
  // @@protoc_insertion_point(class_scope:mqc3_cloud.common.v1.Complex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Complex_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Complex& from_msg);
    float real_;
    float imag_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Complex

// float real = 1 [json_name = "real"];
inline void Complex::clear_real() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.real_ = 0;
}
inline float Complex::real() const {
  // @@protoc_insertion_point(field_get:mqc3_cloud.common.v1.Complex.real)
  return _internal_real();
}
inline void Complex::set_real(float value) {
  _internal_set_real(value);
  // @@protoc_insertion_point(field_set:mqc3_cloud.common.v1.Complex.real)
}
inline float Complex::_internal_real() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.real_;
}
inline void Complex::_internal_set_real(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.real_ = value;
}

// float imag = 2 [json_name = "imag"];
inline void Complex::clear_imag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imag_ = 0;
}
inline float Complex::imag() const {
  // @@protoc_insertion_point(field_get:mqc3_cloud.common.v1.Complex.imag)
  return _internal_imag();
}
inline void Complex::set_imag(float value) {
  _internal_set_imag(value);
  // @@protoc_insertion_point(field_set:mqc3_cloud.common.v1.Complex.imag)
}
inline float Complex::_internal_imag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.imag_;
}
inline void Complex::_internal_set_imag(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imag_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto_2epb_2eh
