// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/common/v1/math.proto
// Protobuf C++ Version: 5.28.3

#include "mqc3_cloud/common/v1/math.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mqc3_cloud {
namespace common {
namespace v1 {

inline constexpr Complex::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : real_{0},
        imag_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Complex::Complex(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ComplexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ComplexDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ComplexDefaultTypeInternal() {}
  union {
    Complex _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ComplexDefaultTypeInternal _Complex_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto = nullptr;
const ::uint32_t
    TableStruct_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::Complex, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::Complex, _impl_.real_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::common::v1::Complex, _impl_.imag_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::mqc3_cloud::common::v1::Complex)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::mqc3_cloud::common::v1::_Complex_default_instance_._instance,
};
const char descriptor_table_protodef_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037mqc3_cloud/common/v1/math.proto\022\024mqc3_"
    "cloud.common.v1\"1\n\007Complex\022\022\n\004real\030\001 \001(\002"
    "R\004real\022\022\n\004imag\030\002 \001(\002R\004imagB\223\001\n\030com.mqc3_"
    "cloud.common.v1B\tMathProtoP\001\242\002\003MCX\252\002\023Mqc"
    "3Cloud.Common.V1\312\002\023Mqc3Cloud\\Common\\V1\342\002"
    "\037Mqc3Cloud\\Common\\V1\\GPBMetadata\352\002\025Mqc3C"
    "loud::Common::V1b\006proto3"
};
static ::absl::once_flag descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto = {
    false,
    false,
    264,
    descriptor_table_protodef_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto,
    "mqc3_cloud/common/v1/math.proto",
    &descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto::offsets,
    file_level_enum_descriptors_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto,
    file_level_service_descriptors_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto,
};
namespace mqc3_cloud {
namespace common {
namespace v1 {
// ===================================================================

class Complex::_Internal {
 public:
};

Complex::Complex(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mqc3_cloud.common.v1.Complex)
}
Complex::Complex(
    ::google::protobuf::Arena* arena, const Complex& from)
    : Complex(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Complex::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Complex::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, real_),
           0,
           offsetof(Impl_, imag_) -
               offsetof(Impl_, real_) +
               sizeof(Impl_::imag_));
}
Complex::~Complex() {
  // @@protoc_insertion_point(destructor:mqc3_cloud.common.v1.Complex)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Complex::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Complex::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Complex_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Complex::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Complex>(),
            ::google::protobuf::Message::GetNewImpl<Complex>(),
            ::google::protobuf::Message::GetClearImpl<Complex>(), &Complex::ByteSizeLong,
                &Complex::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Complex, _impl_._cached_size_),
            false,
        },
        &Complex::kDescriptorMethods,
        &descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Complex::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Complex::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mqc3_cloud::common::v1::Complex>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float imag = 2 [json_name = "imag"];
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(Complex, _impl_.imag_)}},
    // float real = 1 [json_name = "real"];
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(Complex, _impl_.real_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float real = 1 [json_name = "real"];
    {PROTOBUF_FIELD_OFFSET(Complex, _impl_.real_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float imag = 2 [json_name = "imag"];
    {PROTOBUF_FIELD_OFFSET(Complex, _impl_.imag_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Complex::Clear() {
// @@protoc_insertion_point(message_clear_start:mqc3_cloud.common.v1.Complex)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.real_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.imag_) -
      reinterpret_cast<char*>(&_impl_.real_)) + sizeof(_impl_.imag_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Complex::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Complex& this_ = static_cast<const Complex&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Complex::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Complex& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mqc3_cloud.common.v1.Complex)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float real = 1 [json_name = "real"];
          if (::absl::bit_cast<::uint32_t>(this_._internal_real()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_real(), target);
          }

          // float imag = 2 [json_name = "imag"];
          if (::absl::bit_cast<::uint32_t>(this_._internal_imag()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_imag(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mqc3_cloud.common.v1.Complex)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Complex::ByteSizeLong(const MessageLite& base) {
          const Complex& this_ = static_cast<const Complex&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Complex::ByteSizeLong() const {
          const Complex& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mqc3_cloud.common.v1.Complex)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float real = 1 [json_name = "real"];
            if (::absl::bit_cast<::uint32_t>(this_._internal_real()) != 0) {
              total_size += 5;
            }
            // float imag = 2 [json_name = "imag"];
            if (::absl::bit_cast<::uint32_t>(this_._internal_imag()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Complex::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Complex*>(&to_msg);
  auto& from = static_cast<const Complex&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mqc3_cloud.common.v1.Complex)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_real()) != 0) {
    _this->_impl_.real_ = from._impl_.real_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_imag()) != 0) {
    _this->_impl_.imag_ = from._impl_.imag_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Complex::CopyFrom(const Complex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqc3_cloud.common.v1.Complex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Complex::InternalSwap(Complex* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Complex, _impl_.imag_)
      + sizeof(Complex::_impl_.imag_)
      - PROTOBUF_FIELD_OFFSET(Complex, _impl_.real_)>(
          reinterpret_cast<char*>(&_impl_.real_),
          reinterpret_cast<char*>(&other->_impl_.real_));
}

::google::protobuf::Metadata Complex::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mqc3_5fcloud_2fcommon_2fv1_2fmath_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
