// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/program/v1/quantum_program.proto
// Protobuf C++ Version: 5.28.3

#include "mqc3_cloud/program/v1/quantum_program.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mqc3_cloud {
namespace program {
namespace v1 {

inline constexpr QuantumProgramResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        circuit_state_{},
        circuit_result_{nullptr},
        graph_result_{nullptr},
        machinery_result_{nullptr},
        compiled_graph_{nullptr},
        compiled_machinery_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR QuantumProgramResult::QuantumProgramResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct QuantumProgramResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuantumProgramResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuantumProgramResultDefaultTypeInternal() {}
  union {
    QuantumProgramResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuantumProgramResultDefaultTypeInternal _QuantumProgramResult_default_instance_;

inline constexpr QuantumProgram::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : format_{static_cast< ::mqc3_cloud::program::v1::RepresentationFormat >(0)},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR QuantumProgram::QuantumProgram(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct QuantumProgramDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuantumProgramDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuantumProgramDefaultTypeInternal() {}
  union {
    QuantumProgram _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuantumProgramDefaultTypeInternal _QuantumProgram_default_instance_;
}  // namespace v1
}  // namespace program
}  // namespace mqc3_cloud
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto = nullptr;
const ::uint32_t
    TableStruct_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgram, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgram, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgram, _impl_.format_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgram, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_.circuit_result_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_.graph_result_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_.machinery_result_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_.compiled_graph_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_.compiled_machinery_),
        PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgramResult, _impl_.circuit_state_),
        0,
        1,
        2,
        3,
        4,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::mqc3_cloud::program::v1::QuantumProgram)},
        {13, 27, -1, sizeof(::mqc3_cloud::program::v1::QuantumProgramResult)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::mqc3_cloud::program::v1::_QuantumProgram_default_instance_._instance,
    &::mqc3_cloud::program::v1::_QuantumProgramResult_default_instance_._instance,
};
const char descriptor_table_protodef_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n+mqc3_cloud/program/v1/quantum_program."
    "proto\022\025mqc3_cloud.program.v1\032#mqc3_cloud"
    "/program/v1/circuit.proto\032!mqc3_cloud/pr"
    "ogram/v1/graph.proto\032%mqc3_cloud/program"
    "/v1/machinery.proto\"\276\002\n\016QuantumProgram\022C"
    "\n\006format\030\001 \001(\0162+.mqc3_cloud.program.v1.R"
    "epresentationFormatR\006format\022H\n\007circuit\030\002"
    " \001(\0132,.mqc3_cloud.program.v1.CircuitRepr"
    "esentationH\000R\007circuit\022B\n\005graph\030\003 \001(\0132*.m"
    "qc3_cloud.program.v1.GraphRepresentation"
    "H\000R\005graph\022N\n\tmachinery\030\004 \001(\0132..mqc3_clou"
    "d.program.v1.MachineryRepresentationH\000R\t"
    "machineryB\t\n\007payload\"\371\003\n\024QuantumProgramR"
    "esult\022K\n\016circuit_result\030\001 \001(\0132$.mqc3_clo"
    "ud.program.v1.CircuitResultR\rcircuitResu"
    "lt\022E\n\014graph_result\030\002 \001(\0132\".mqc3_cloud.pr"
    "ogram.v1.GraphResultR\013graphResult\022Q\n\020mac"
    "hinery_result\030\003 \001(\0132&.mqc3_cloud.program"
    ".v1.MachineryResultR\017machineryResult\022Q\n\016"
    "compiled_graph\030\004 \001(\0132*.mqc3_cloud.progra"
    "m.v1.GraphRepresentationR\rcompiledGraph\022"
    "]\n\022compiled_machinery\030\005 \001(\0132..mqc3_cloud"
    ".program.v1.MachineryRepresentationR\021com"
    "piledMachinery\022H\n\rcircuit_state\030\006 \003(\0132#."
    "mqc3_cloud.program.v1.BosonicStateR\014circ"
    "uitState*\246\001\n\024RepresentationFormat\022%\n!REP"
    "RESENTATION_FORMAT_UNSPECIFIED\020\000\022!\n\035REPR"
    "ESENTATION_FORMAT_CIRCUIT\020\001\022\037\n\033REPRESENT"
    "ATION_FORMAT_GRAPH\020\002\022#\n\037REPRESENTATION_F"
    "ORMAT_MACHINERY\020\003B\242\001\n\031com.mqc3_cloud.pro"
    "gram.v1B\023QuantumProgramProtoP\001\242\002\003MPX\252\002\024M"
    "qc3Cloud.Program.V1\312\002\024Mqc3Cloud\\Program\\"
    "V1\342\002 Mqc3Cloud\\Program\\V1\\GPBMetadata\352\002\026"
    "Mqc3Cloud::Program::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_deps[3] =
    {
        &::descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fcircuit_2eproto,
        &::descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fgraph_2eproto,
        &::descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fmachinery_2eproto,
};
static ::absl::once_flag descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto = {
    false,
    false,
    1350,
    descriptor_table_protodef_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto,
    "mqc3_cloud/program/v1/quantum_program.proto",
    &descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_once,
    descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_deps,
    3,
    2,
    schemas,
    file_default_instances,
    TableStruct_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto::offsets,
    file_level_enum_descriptors_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto,
    file_level_service_descriptors_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto,
};
namespace mqc3_cloud {
namespace program {
namespace v1 {
const ::google::protobuf::EnumDescriptor* RepresentationFormat_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto);
  return file_level_enum_descriptors_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RepresentationFormat_internal_data_[] = {
    262144u, 0u, };
bool RepresentationFormat_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class QuantumProgram::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::mqc3_cloud::program::v1::QuantumProgram, _impl_._oneof_case_);
};

void QuantumProgram::set_allocated_circuit(::mqc3_cloud::program::v1::CircuitRepresentation* circuit) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (circuit) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(circuit)->GetArena();
    if (message_arena != submessage_arena) {
      circuit = ::google::protobuf::internal::GetOwnedMessage(message_arena, circuit, submessage_arena);
    }
    set_has_circuit();
    _impl_.payload_.circuit_ = circuit;
  }
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgram.circuit)
}
void QuantumProgram::clear_circuit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kCircuit) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.circuit_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.circuit_);
    }
    clear_has_payload();
  }
}
void QuantumProgram::set_allocated_graph(::mqc3_cloud::program::v1::GraphRepresentation* graph) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (graph) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(graph)->GetArena();
    if (message_arena != submessage_arena) {
      graph = ::google::protobuf::internal::GetOwnedMessage(message_arena, graph, submessage_arena);
    }
    set_has_graph();
    _impl_.payload_.graph_ = graph;
  }
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgram.graph)
}
void QuantumProgram::clear_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kGraph) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.graph_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.graph_);
    }
    clear_has_payload();
  }
}
void QuantumProgram::set_allocated_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* machinery) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (machinery) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(machinery)->GetArena();
    if (message_arena != submessage_arena) {
      machinery = ::google::protobuf::internal::GetOwnedMessage(message_arena, machinery, submessage_arena);
    }
    set_has_machinery();
    _impl_.payload_.machinery_ = machinery;
  }
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgram.machinery)
}
void QuantumProgram::clear_machinery() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMachinery) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.machinery_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.machinery_);
    }
    clear_has_payload();
  }
}
QuantumProgram::QuantumProgram(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mqc3_cloud.program.v1.QuantumProgram)
}
inline PROTOBUF_NDEBUG_INLINE QuantumProgram::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mqc3_cloud::program::v1::QuantumProgram& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

QuantumProgram::QuantumProgram(
    ::google::protobuf::Arena* arena,
    const QuantumProgram& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QuantumProgram* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.format_ = from._impl_.format_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kCircuit:
        _impl_.payload_.circuit_ = ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::CircuitRepresentation>(arena, *from._impl_.payload_.circuit_);
        break;
      case kGraph:
        _impl_.payload_.graph_ = ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::GraphRepresentation>(arena, *from._impl_.payload_.graph_);
        break;
      case kMachinery:
        _impl_.payload_.machinery_ = ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::MachineryRepresentation>(arena, *from._impl_.payload_.machinery_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:mqc3_cloud.program.v1.QuantumProgram)
}
inline PROTOBUF_NDEBUG_INLINE QuantumProgram::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void QuantumProgram::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.format_ = {};
}
QuantumProgram::~QuantumProgram() {
  // @@protoc_insertion_point(destructor:mqc3_cloud.program.v1.QuantumProgram)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void QuantumProgram::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
  _impl_.~Impl_();
}

void QuantumProgram::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:mqc3_cloud.program.v1.QuantumProgram)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kCircuit: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.circuit_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.circuit_);
      }
      break;
    }
    case kGraph: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.graph_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.graph_);
      }
      break;
    }
    case kMachinery: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.machinery_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.machinery_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    QuantumProgram::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_QuantumProgram_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &QuantumProgram::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<QuantumProgram>(),
            ::google::protobuf::Message::GetNewImpl<QuantumProgram>(),
            ::google::protobuf::Message::GetClearImpl<QuantumProgram>(), &QuantumProgram::ByteSizeLong,
                &QuantumProgram::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(QuantumProgram, _impl_._cached_size_),
            false,
        },
        &QuantumProgram::kDescriptorMethods,
        &descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* QuantumProgram::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 3, 0, 2> QuantumProgram::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::QuantumProgram>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .mqc3_cloud.program.v1.RepresentationFormat format = 1 [json_name = "format"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(QuantumProgram, _impl_.format_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(QuantumProgram, _impl_.format_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .mqc3_cloud.program.v1.RepresentationFormat format = 1 [json_name = "format"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgram, _impl_.format_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .mqc3_cloud.program.v1.CircuitRepresentation circuit = 2 [json_name = "circuit"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgram, _impl_.payload_.circuit_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .mqc3_cloud.program.v1.GraphRepresentation graph = 3 [json_name = "graph"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgram, _impl_.payload_.graph_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .mqc3_cloud.program.v1.MachineryRepresentation machinery = 4 [json_name = "machinery"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgram, _impl_.payload_.machinery_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::CircuitRepresentation>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::GraphRepresentation>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::MachineryRepresentation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void QuantumProgram::Clear() {
// @@protoc_insertion_point(message_clear_start:mqc3_cloud.program.v1.QuantumProgram)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.format_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* QuantumProgram::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const QuantumProgram& this_ = static_cast<const QuantumProgram&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* QuantumProgram::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const QuantumProgram& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mqc3_cloud.program.v1.QuantumProgram)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .mqc3_cloud.program.v1.RepresentationFormat format = 1 [json_name = "format"];
          if (this_._internal_format() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_format(), target);
          }

          switch (this_.payload_case()) {
            case kCircuit: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.payload_.circuit_, this_._impl_.payload_.circuit_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kGraph: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  3, *this_._impl_.payload_.graph_, this_._impl_.payload_.graph_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kMachinery: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  4, *this_._impl_.payload_.machinery_, this_._impl_.payload_.machinery_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mqc3_cloud.program.v1.QuantumProgram)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t QuantumProgram::ByteSizeLong(const MessageLite& base) {
          const QuantumProgram& this_ = static_cast<const QuantumProgram&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t QuantumProgram::ByteSizeLong() const {
          const QuantumProgram& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mqc3_cloud.program.v1.QuantumProgram)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .mqc3_cloud.program.v1.RepresentationFormat format = 1 [json_name = "format"];
            if (this_._internal_format() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_format());
            }
          }
          switch (this_.payload_case()) {
            // .mqc3_cloud.program.v1.CircuitRepresentation circuit = 2 [json_name = "circuit"];
            case kCircuit: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.circuit_);
              break;
            }
            // .mqc3_cloud.program.v1.GraphRepresentation graph = 3 [json_name = "graph"];
            case kGraph: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.graph_);
              break;
            }
            // .mqc3_cloud.program.v1.MachineryRepresentation machinery = 4 [json_name = "machinery"];
            case kMachinery: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.machinery_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void QuantumProgram::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<QuantumProgram*>(&to_msg);
  auto& from = static_cast<const QuantumProgram&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:mqc3_cloud.program.v1.QuantumProgram)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_format() != 0) {
    _this->_impl_.format_ = from._impl_.format_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kCircuit: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.circuit_ =
              ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::CircuitRepresentation>(arena, *from._impl_.payload_.circuit_);
        } else {
          _this->_impl_.payload_.circuit_->MergeFrom(from._internal_circuit());
        }
        break;
      }
      case kGraph: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.graph_ =
              ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::GraphRepresentation>(arena, *from._impl_.payload_.graph_);
        } else {
          _this->_impl_.payload_.graph_->MergeFrom(from._internal_graph());
        }
        break;
      }
      case kMachinery: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.machinery_ =
              ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::MachineryRepresentation>(arena, *from._impl_.payload_.machinery_);
        } else {
          _this->_impl_.payload_.machinery_->MergeFrom(from._internal_machinery());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void QuantumProgram::CopyFrom(const QuantumProgram& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqc3_cloud.program.v1.QuantumProgram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QuantumProgram::InternalSwap(QuantumProgram* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.format_, other->_impl_.format_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata QuantumProgram::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class QuantumProgramResult::_Internal {
 public:
  using HasBits =
      decltype(std::declval<QuantumProgramResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_._has_bits_);
};

void QuantumProgramResult::clear_circuit_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.circuit_result_ != nullptr) _impl_.circuit_result_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void QuantumProgramResult::clear_graph_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.graph_result_ != nullptr) _impl_.graph_result_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void QuantumProgramResult::clear_machinery_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.machinery_result_ != nullptr) _impl_.machinery_result_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void QuantumProgramResult::clear_compiled_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.compiled_graph_ != nullptr) _impl_.compiled_graph_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void QuantumProgramResult::clear_compiled_machinery() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.compiled_machinery_ != nullptr) _impl_.compiled_machinery_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
void QuantumProgramResult::clear_circuit_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.circuit_state_.Clear();
}
QuantumProgramResult::QuantumProgramResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mqc3_cloud.program.v1.QuantumProgramResult)
}
inline PROTOBUF_NDEBUG_INLINE QuantumProgramResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mqc3_cloud::program::v1::QuantumProgramResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        circuit_state_{visibility, arena, from.circuit_state_} {}

QuantumProgramResult::QuantumProgramResult(
    ::google::protobuf::Arena* arena,
    const QuantumProgramResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QuantumProgramResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.circuit_result_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::CircuitResult>(
                              arena, *from._impl_.circuit_result_)
                        : nullptr;
  _impl_.graph_result_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::GraphResult>(
                              arena, *from._impl_.graph_result_)
                        : nullptr;
  _impl_.machinery_result_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::MachineryResult>(
                              arena, *from._impl_.machinery_result_)
                        : nullptr;
  _impl_.compiled_graph_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::GraphRepresentation>(
                              arena, *from._impl_.compiled_graph_)
                        : nullptr;
  _impl_.compiled_machinery_ = (cached_has_bits & 0x00000010u) ? ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::MachineryRepresentation>(
                              arena, *from._impl_.compiled_machinery_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:mqc3_cloud.program.v1.QuantumProgramResult)
}
inline PROTOBUF_NDEBUG_INLINE QuantumProgramResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        circuit_state_{visibility, arena} {}

inline void QuantumProgramResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, circuit_result_),
           0,
           offsetof(Impl_, compiled_machinery_) -
               offsetof(Impl_, circuit_result_) +
               sizeof(Impl_::compiled_machinery_));
}
QuantumProgramResult::~QuantumProgramResult() {
  // @@protoc_insertion_point(destructor:mqc3_cloud.program.v1.QuantumProgramResult)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void QuantumProgramResult::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.circuit_result_;
  delete _impl_.graph_result_;
  delete _impl_.machinery_result_;
  delete _impl_.compiled_graph_;
  delete _impl_.compiled_machinery_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    QuantumProgramResult::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_QuantumProgramResult_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &QuantumProgramResult::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<QuantumProgramResult>(),
            ::google::protobuf::Message::GetNewImpl<QuantumProgramResult>(),
            ::google::protobuf::Message::GetClearImpl<QuantumProgramResult>(), &QuantumProgramResult::ByteSizeLong,
                &QuantumProgramResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_._cached_size_),
            false,
        },
        &QuantumProgramResult::kDescriptorMethods,
        &descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* QuantumProgramResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 6, 0, 2> QuantumProgramResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    6,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::QuantumProgramResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .mqc3_cloud.program.v1.CircuitResult circuit_result = 1 [json_name = "circuitResult"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.circuit_result_)}},
    // .mqc3_cloud.program.v1.GraphResult graph_result = 2 [json_name = "graphResult"];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.graph_result_)}},
    // .mqc3_cloud.program.v1.MachineryResult machinery_result = 3 [json_name = "machineryResult"];
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.machinery_result_)}},
    // .mqc3_cloud.program.v1.GraphRepresentation compiled_graph = 4 [json_name = "compiledGraph"];
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.compiled_graph_)}},
    // .mqc3_cloud.program.v1.MachineryRepresentation compiled_machinery = 5 [json_name = "compiledMachinery"];
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 4, PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.compiled_machinery_)}},
    // repeated .mqc3_cloud.program.v1.BosonicState circuit_state = 6 [json_name = "circuitState"];
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 5, PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.circuit_state_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .mqc3_cloud.program.v1.CircuitResult circuit_result = 1 [json_name = "circuitResult"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.circuit_result_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .mqc3_cloud.program.v1.GraphResult graph_result = 2 [json_name = "graphResult"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.graph_result_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .mqc3_cloud.program.v1.MachineryResult machinery_result = 3 [json_name = "machineryResult"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.machinery_result_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .mqc3_cloud.program.v1.GraphRepresentation compiled_graph = 4 [json_name = "compiledGraph"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.compiled_graph_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .mqc3_cloud.program.v1.MachineryRepresentation compiled_machinery = 5 [json_name = "compiledMachinery"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.compiled_machinery_), _Internal::kHasBitsOffset + 4, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .mqc3_cloud.program.v1.BosonicState circuit_state = 6 [json_name = "circuitState"];
    {PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.circuit_state_), -1, 5,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::CircuitResult>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::GraphResult>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::MachineryResult>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::GraphRepresentation>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::MachineryRepresentation>()},
    {::_pbi::TcParser::GetTable<::mqc3_cloud::program::v1::BosonicState>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void QuantumProgramResult::Clear() {
// @@protoc_insertion_point(message_clear_start:mqc3_cloud.program.v1.QuantumProgramResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.circuit_state_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.circuit_result_ != nullptr);
      _impl_.circuit_result_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.graph_result_ != nullptr);
      _impl_.graph_result_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.machinery_result_ != nullptr);
      _impl_.machinery_result_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.compiled_graph_ != nullptr);
      _impl_.compiled_graph_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(_impl_.compiled_machinery_ != nullptr);
      _impl_.compiled_machinery_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* QuantumProgramResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const QuantumProgramResult& this_ = static_cast<const QuantumProgramResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* QuantumProgramResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const QuantumProgramResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mqc3_cloud.program.v1.QuantumProgramResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .mqc3_cloud.program.v1.CircuitResult circuit_result = 1 [json_name = "circuitResult"];
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.circuit_result_, this_._impl_.circuit_result_->GetCachedSize(), target,
                stream);
          }

          // .mqc3_cloud.program.v1.GraphResult graph_result = 2 [json_name = "graphResult"];
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.graph_result_, this_._impl_.graph_result_->GetCachedSize(), target,
                stream);
          }

          // .mqc3_cloud.program.v1.MachineryResult machinery_result = 3 [json_name = "machineryResult"];
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.machinery_result_, this_._impl_.machinery_result_->GetCachedSize(), target,
                stream);
          }

          // .mqc3_cloud.program.v1.GraphRepresentation compiled_graph = 4 [json_name = "compiledGraph"];
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.compiled_graph_, this_._impl_.compiled_graph_->GetCachedSize(), target,
                stream);
          }

          // .mqc3_cloud.program.v1.MachineryRepresentation compiled_machinery = 5 [json_name = "compiledMachinery"];
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                5, *this_._impl_.compiled_machinery_, this_._impl_.compiled_machinery_->GetCachedSize(), target,
                stream);
          }

          // repeated .mqc3_cloud.program.v1.BosonicState circuit_state = 6 [json_name = "circuitState"];
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_circuit_state_size());
               i < n; i++) {
            const auto& repfield = this_._internal_circuit_state().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    6, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mqc3_cloud.program.v1.QuantumProgramResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t QuantumProgramResult::ByteSizeLong(const MessageLite& base) {
          const QuantumProgramResult& this_ = static_cast<const QuantumProgramResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t QuantumProgramResult::ByteSizeLong() const {
          const QuantumProgramResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mqc3_cloud.program.v1.QuantumProgramResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .mqc3_cloud.program.v1.BosonicState circuit_state = 6 [json_name = "circuitState"];
             {
              total_size += 1UL * this_._internal_circuit_state_size();
              for (const auto& msg : this_._internal_circuit_state()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000001fu) {
            // .mqc3_cloud.program.v1.CircuitResult circuit_result = 1 [json_name = "circuitResult"];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.circuit_result_);
            }
            // .mqc3_cloud.program.v1.GraphResult graph_result = 2 [json_name = "graphResult"];
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.graph_result_);
            }
            // .mqc3_cloud.program.v1.MachineryResult machinery_result = 3 [json_name = "machineryResult"];
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.machinery_result_);
            }
            // .mqc3_cloud.program.v1.GraphRepresentation compiled_graph = 4 [json_name = "compiledGraph"];
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.compiled_graph_);
            }
            // .mqc3_cloud.program.v1.MachineryRepresentation compiled_machinery = 5 [json_name = "compiledMachinery"];
            if (cached_has_bits & 0x00000010u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.compiled_machinery_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void QuantumProgramResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<QuantumProgramResult*>(&to_msg);
  auto& from = static_cast<const QuantumProgramResult&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:mqc3_cloud.program.v1.QuantumProgramResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_circuit_state()->MergeFrom(
      from._internal_circuit_state());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.circuit_result_ != nullptr);
      if (_this->_impl_.circuit_result_ == nullptr) {
        _this->_impl_.circuit_result_ =
            ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::CircuitResult>(arena, *from._impl_.circuit_result_);
      } else {
        _this->_impl_.circuit_result_->MergeFrom(*from._impl_.circuit_result_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.graph_result_ != nullptr);
      if (_this->_impl_.graph_result_ == nullptr) {
        _this->_impl_.graph_result_ =
            ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::GraphResult>(arena, *from._impl_.graph_result_);
      } else {
        _this->_impl_.graph_result_->MergeFrom(*from._impl_.graph_result_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.machinery_result_ != nullptr);
      if (_this->_impl_.machinery_result_ == nullptr) {
        _this->_impl_.machinery_result_ =
            ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::MachineryResult>(arena, *from._impl_.machinery_result_);
      } else {
        _this->_impl_.machinery_result_->MergeFrom(*from._impl_.machinery_result_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.compiled_graph_ != nullptr);
      if (_this->_impl_.compiled_graph_ == nullptr) {
        _this->_impl_.compiled_graph_ =
            ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::GraphRepresentation>(arena, *from._impl_.compiled_graph_);
      } else {
        _this->_impl_.compiled_graph_->MergeFrom(*from._impl_.compiled_graph_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(from._impl_.compiled_machinery_ != nullptr);
      if (_this->_impl_.compiled_machinery_ == nullptr) {
        _this->_impl_.compiled_machinery_ =
            ::google::protobuf::Message::CopyConstruct<::mqc3_cloud::program::v1::MachineryRepresentation>(arena, *from._impl_.compiled_machinery_);
      } else {
        _this->_impl_.compiled_machinery_->MergeFrom(*from._impl_.compiled_machinery_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void QuantumProgramResult::CopyFrom(const QuantumProgramResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqc3_cloud.program.v1.QuantumProgramResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QuantumProgramResult::InternalSwap(QuantumProgramResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.circuit_state_.InternalSwap(&other->_impl_.circuit_state_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.compiled_machinery_)
      + sizeof(QuantumProgramResult::_impl_.compiled_machinery_)
      - PROTOBUF_FIELD_OFFSET(QuantumProgramResult, _impl_.circuit_result_)>(
          reinterpret_cast<char*>(&_impl_.circuit_result_),
          reinterpret_cast<char*>(&other->_impl_.circuit_result_));
}

::google::protobuf::Metadata QuantumProgramResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace program
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
