// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mqc3_cloud/program/v1/quantum_program.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "mqc3_cloud/program/v1/circuit.pb.h"
#include "mqc3_cloud/program/v1/graph.pb.h"
#include "mqc3_cloud/program/v1/machinery.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto;
namespace mqc3_cloud {
namespace program {
namespace v1 {
class QuantumProgram;
struct QuantumProgramDefaultTypeInternal;
extern QuantumProgramDefaultTypeInternal _QuantumProgram_default_instance_;
class QuantumProgramResult;
struct QuantumProgramResultDefaultTypeInternal;
extern QuantumProgramResultDefaultTypeInternal _QuantumProgramResult_default_instance_;
}  // namespace v1
}  // namespace program
}  // namespace mqc3_cloud
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mqc3_cloud {
namespace program {
namespace v1 {
enum RepresentationFormat : int {
  REPRESENTATION_FORMAT_UNSPECIFIED = 0,
  REPRESENTATION_FORMAT_CIRCUIT = 1,
  REPRESENTATION_FORMAT_GRAPH = 2,
  REPRESENTATION_FORMAT_MACHINERY = 3,
  RepresentationFormat_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RepresentationFormat_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RepresentationFormat_IsValid(int value);
extern const uint32_t RepresentationFormat_internal_data_[];
constexpr RepresentationFormat RepresentationFormat_MIN = static_cast<RepresentationFormat>(0);
constexpr RepresentationFormat RepresentationFormat_MAX = static_cast<RepresentationFormat>(3);
constexpr int RepresentationFormat_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
RepresentationFormat_descriptor();
template <typename T>
const std::string& RepresentationFormat_Name(T value) {
  static_assert(std::is_same<T, RepresentationFormat>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RepresentationFormat_Name().");
  return RepresentationFormat_Name(static_cast<RepresentationFormat>(value));
}
template <>
inline const std::string& RepresentationFormat_Name(RepresentationFormat value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RepresentationFormat_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool RepresentationFormat_Parse(absl::string_view name, RepresentationFormat* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RepresentationFormat>(
      RepresentationFormat_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class QuantumProgramResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqc3_cloud.program.v1.QuantumProgramResult) */ {
 public:
  inline QuantumProgramResult() : QuantumProgramResult(nullptr) {}
  ~QuantumProgramResult() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QuantumProgramResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline QuantumProgramResult(const QuantumProgramResult& from) : QuantumProgramResult(nullptr, from) {}
  inline QuantumProgramResult(QuantumProgramResult&& from) noexcept
      : QuantumProgramResult(nullptr, std::move(from)) {}
  inline QuantumProgramResult& operator=(const QuantumProgramResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuantumProgramResult& operator=(QuantumProgramResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuantumProgramResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const QuantumProgramResult* internal_default_instance() {
    return reinterpret_cast<const QuantumProgramResult*>(
        &_QuantumProgramResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(QuantumProgramResult& a, QuantumProgramResult& b) { a.Swap(&b); }
  inline void Swap(QuantumProgramResult* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuantumProgramResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuantumProgramResult* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<QuantumProgramResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QuantumProgramResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QuantumProgramResult& from) { QuantumProgramResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(QuantumProgramResult* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mqc3_cloud.program.v1.QuantumProgramResult"; }

 protected:
  explicit QuantumProgramResult(::google::protobuf::Arena* arena);
  QuantumProgramResult(::google::protobuf::Arena* arena, const QuantumProgramResult& from);
  QuantumProgramResult(::google::protobuf::Arena* arena, QuantumProgramResult&& from) noexcept
      : QuantumProgramResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCircuitStateFieldNumber = 6,
    kCircuitResultFieldNumber = 1,
    kGraphResultFieldNumber = 2,
    kMachineryResultFieldNumber = 3,
    kCompiledGraphFieldNumber = 4,
    kCompiledMachineryFieldNumber = 5,
  };
  // repeated .mqc3_cloud.program.v1.BosonicState circuit_state = 6 [json_name = "circuitState"];
  int circuit_state_size() const;
  private:
  int _internal_circuit_state_size() const;

  public:
  void clear_circuit_state() ;
  ::mqc3_cloud::program::v1::BosonicState* mutable_circuit_state(int index);
  ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>* mutable_circuit_state();

  private:
  const ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>& _internal_circuit_state() const;
  ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>* _internal_mutable_circuit_state();
  public:
  const ::mqc3_cloud::program::v1::BosonicState& circuit_state(int index) const;
  ::mqc3_cloud::program::v1::BosonicState* add_circuit_state();
  const ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>& circuit_state() const;
  // .mqc3_cloud.program.v1.CircuitResult circuit_result = 1 [json_name = "circuitResult"];
  bool has_circuit_result() const;
  void clear_circuit_result() ;
  const ::mqc3_cloud::program::v1::CircuitResult& circuit_result() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::CircuitResult* release_circuit_result();
  ::mqc3_cloud::program::v1::CircuitResult* mutable_circuit_result();
  void set_allocated_circuit_result(::mqc3_cloud::program::v1::CircuitResult* value);
  void unsafe_arena_set_allocated_circuit_result(::mqc3_cloud::program::v1::CircuitResult* value);
  ::mqc3_cloud::program::v1::CircuitResult* unsafe_arena_release_circuit_result();

  private:
  const ::mqc3_cloud::program::v1::CircuitResult& _internal_circuit_result() const;
  ::mqc3_cloud::program::v1::CircuitResult* _internal_mutable_circuit_result();

  public:
  // .mqc3_cloud.program.v1.GraphResult graph_result = 2 [json_name = "graphResult"];
  bool has_graph_result() const;
  void clear_graph_result() ;
  const ::mqc3_cloud::program::v1::GraphResult& graph_result() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::GraphResult* release_graph_result();
  ::mqc3_cloud::program::v1::GraphResult* mutable_graph_result();
  void set_allocated_graph_result(::mqc3_cloud::program::v1::GraphResult* value);
  void unsafe_arena_set_allocated_graph_result(::mqc3_cloud::program::v1::GraphResult* value);
  ::mqc3_cloud::program::v1::GraphResult* unsafe_arena_release_graph_result();

  private:
  const ::mqc3_cloud::program::v1::GraphResult& _internal_graph_result() const;
  ::mqc3_cloud::program::v1::GraphResult* _internal_mutable_graph_result();

  public:
  // .mqc3_cloud.program.v1.MachineryResult machinery_result = 3 [json_name = "machineryResult"];
  bool has_machinery_result() const;
  void clear_machinery_result() ;
  const ::mqc3_cloud::program::v1::MachineryResult& machinery_result() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::MachineryResult* release_machinery_result();
  ::mqc3_cloud::program::v1::MachineryResult* mutable_machinery_result();
  void set_allocated_machinery_result(::mqc3_cloud::program::v1::MachineryResult* value);
  void unsafe_arena_set_allocated_machinery_result(::mqc3_cloud::program::v1::MachineryResult* value);
  ::mqc3_cloud::program::v1::MachineryResult* unsafe_arena_release_machinery_result();

  private:
  const ::mqc3_cloud::program::v1::MachineryResult& _internal_machinery_result() const;
  ::mqc3_cloud::program::v1::MachineryResult* _internal_mutable_machinery_result();

  public:
  // .mqc3_cloud.program.v1.GraphRepresentation compiled_graph = 4 [json_name = "compiledGraph"];
  bool has_compiled_graph() const;
  void clear_compiled_graph() ;
  const ::mqc3_cloud::program::v1::GraphRepresentation& compiled_graph() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::GraphRepresentation* release_compiled_graph();
  ::mqc3_cloud::program::v1::GraphRepresentation* mutable_compiled_graph();
  void set_allocated_compiled_graph(::mqc3_cloud::program::v1::GraphRepresentation* value);
  void unsafe_arena_set_allocated_compiled_graph(::mqc3_cloud::program::v1::GraphRepresentation* value);
  ::mqc3_cloud::program::v1::GraphRepresentation* unsafe_arena_release_compiled_graph();

  private:
  const ::mqc3_cloud::program::v1::GraphRepresentation& _internal_compiled_graph() const;
  ::mqc3_cloud::program::v1::GraphRepresentation* _internal_mutable_compiled_graph();

  public:
  // .mqc3_cloud.program.v1.MachineryRepresentation compiled_machinery = 5 [json_name = "compiledMachinery"];
  bool has_compiled_machinery() const;
  void clear_compiled_machinery() ;
  const ::mqc3_cloud::program::v1::MachineryRepresentation& compiled_machinery() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::MachineryRepresentation* release_compiled_machinery();
  ::mqc3_cloud::program::v1::MachineryRepresentation* mutable_compiled_machinery();
  void set_allocated_compiled_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value);
  void unsafe_arena_set_allocated_compiled_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value);
  ::mqc3_cloud::program::v1::MachineryRepresentation* unsafe_arena_release_compiled_machinery();

  private:
  const ::mqc3_cloud::program::v1::MachineryRepresentation& _internal_compiled_machinery() const;
  ::mqc3_cloud::program::v1::MachineryRepresentation* _internal_mutable_compiled_machinery();

  public:
  // @@protoc_insertion_point(class_scope:mqc3_cloud.program.v1.QuantumProgramResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 6,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_QuantumProgramResult_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const QuantumProgramResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::mqc3_cloud::program::v1::BosonicState > circuit_state_;
    ::mqc3_cloud::program::v1::CircuitResult* circuit_result_;
    ::mqc3_cloud::program::v1::GraphResult* graph_result_;
    ::mqc3_cloud::program::v1::MachineryResult* machinery_result_;
    ::mqc3_cloud::program::v1::GraphRepresentation* compiled_graph_;
    ::mqc3_cloud::program::v1::MachineryRepresentation* compiled_machinery_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto;
};
// -------------------------------------------------------------------

class QuantumProgram final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqc3_cloud.program.v1.QuantumProgram) */ {
 public:
  inline QuantumProgram() : QuantumProgram(nullptr) {}
  ~QuantumProgram() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QuantumProgram(
      ::google::protobuf::internal::ConstantInitialized);

  inline QuantumProgram(const QuantumProgram& from) : QuantumProgram(nullptr, from) {}
  inline QuantumProgram(QuantumProgram&& from) noexcept
      : QuantumProgram(nullptr, std::move(from)) {}
  inline QuantumProgram& operator=(const QuantumProgram& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuantumProgram& operator=(QuantumProgram&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuantumProgram& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kCircuit = 2,
    kGraph = 3,
    kMachinery = 4,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const QuantumProgram* internal_default_instance() {
    return reinterpret_cast<const QuantumProgram*>(
        &_QuantumProgram_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(QuantumProgram& a, QuantumProgram& b) { a.Swap(&b); }
  inline void Swap(QuantumProgram* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuantumProgram* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuantumProgram* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<QuantumProgram>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QuantumProgram& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QuantumProgram& from) { QuantumProgram::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(QuantumProgram* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mqc3_cloud.program.v1.QuantumProgram"; }

 protected:
  explicit QuantumProgram(::google::protobuf::Arena* arena);
  QuantumProgram(::google::protobuf::Arena* arena, const QuantumProgram& from);
  QuantumProgram(::google::protobuf::Arena* arena, QuantumProgram&& from) noexcept
      : QuantumProgram(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFormatFieldNumber = 1,
    kCircuitFieldNumber = 2,
    kGraphFieldNumber = 3,
    kMachineryFieldNumber = 4,
  };
  // .mqc3_cloud.program.v1.RepresentationFormat format = 1 [json_name = "format"];
  void clear_format() ;
  ::mqc3_cloud::program::v1::RepresentationFormat format() const;
  void set_format(::mqc3_cloud::program::v1::RepresentationFormat value);

  private:
  ::mqc3_cloud::program::v1::RepresentationFormat _internal_format() const;
  void _internal_set_format(::mqc3_cloud::program::v1::RepresentationFormat value);

  public:
  // .mqc3_cloud.program.v1.CircuitRepresentation circuit = 2 [json_name = "circuit"];
  bool has_circuit() const;
  private:
  bool _internal_has_circuit() const;

  public:
  void clear_circuit() ;
  const ::mqc3_cloud::program::v1::CircuitRepresentation& circuit() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::CircuitRepresentation* release_circuit();
  ::mqc3_cloud::program::v1::CircuitRepresentation* mutable_circuit();
  void set_allocated_circuit(::mqc3_cloud::program::v1::CircuitRepresentation* value);
  void unsafe_arena_set_allocated_circuit(::mqc3_cloud::program::v1::CircuitRepresentation* value);
  ::mqc3_cloud::program::v1::CircuitRepresentation* unsafe_arena_release_circuit();

  private:
  const ::mqc3_cloud::program::v1::CircuitRepresentation& _internal_circuit() const;
  ::mqc3_cloud::program::v1::CircuitRepresentation* _internal_mutable_circuit();

  public:
  // .mqc3_cloud.program.v1.GraphRepresentation graph = 3 [json_name = "graph"];
  bool has_graph() const;
  private:
  bool _internal_has_graph() const;

  public:
  void clear_graph() ;
  const ::mqc3_cloud::program::v1::GraphRepresentation& graph() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::GraphRepresentation* release_graph();
  ::mqc3_cloud::program::v1::GraphRepresentation* mutable_graph();
  void set_allocated_graph(::mqc3_cloud::program::v1::GraphRepresentation* value);
  void unsafe_arena_set_allocated_graph(::mqc3_cloud::program::v1::GraphRepresentation* value);
  ::mqc3_cloud::program::v1::GraphRepresentation* unsafe_arena_release_graph();

  private:
  const ::mqc3_cloud::program::v1::GraphRepresentation& _internal_graph() const;
  ::mqc3_cloud::program::v1::GraphRepresentation* _internal_mutable_graph();

  public:
  // .mqc3_cloud.program.v1.MachineryRepresentation machinery = 4 [json_name = "machinery"];
  bool has_machinery() const;
  private:
  bool _internal_has_machinery() const;

  public:
  void clear_machinery() ;
  const ::mqc3_cloud::program::v1::MachineryRepresentation& machinery() const;
  PROTOBUF_NODISCARD ::mqc3_cloud::program::v1::MachineryRepresentation* release_machinery();
  ::mqc3_cloud::program::v1::MachineryRepresentation* mutable_machinery();
  void set_allocated_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value);
  void unsafe_arena_set_allocated_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value);
  ::mqc3_cloud::program::v1::MachineryRepresentation* unsafe_arena_release_machinery();

  private:
  const ::mqc3_cloud::program::v1::MachineryRepresentation& _internal_machinery() const;
  ::mqc3_cloud::program::v1::MachineryRepresentation* _internal_mutable_machinery();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:mqc3_cloud.program.v1.QuantumProgram)
 private:
  class _Internal;
  void set_has_circuit();
  void set_has_graph();
  void set_has_machinery();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 4, 3,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_QuantumProgram_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const QuantumProgram& from_msg);
    int format_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::mqc3_cloud::program::v1::CircuitRepresentation* circuit_;
      ::mqc3_cloud::program::v1::GraphRepresentation* graph_;
      ::mqc3_cloud::program::v1::MachineryRepresentation* machinery_;
    } payload_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// QuantumProgram

// .mqc3_cloud.program.v1.RepresentationFormat format = 1 [json_name = "format"];
inline void QuantumProgram::clear_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_ = 0;
}
inline ::mqc3_cloud::program::v1::RepresentationFormat QuantumProgram::format() const {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgram.format)
  return _internal_format();
}
inline void QuantumProgram::set_format(::mqc3_cloud::program::v1::RepresentationFormat value) {
  _internal_set_format(value);
  // @@protoc_insertion_point(field_set:mqc3_cloud.program.v1.QuantumProgram.format)
}
inline ::mqc3_cloud::program::v1::RepresentationFormat QuantumProgram::_internal_format() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mqc3_cloud::program::v1::RepresentationFormat>(_impl_.format_);
}
inline void QuantumProgram::_internal_set_format(::mqc3_cloud::program::v1::RepresentationFormat value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_ = value;
}

// .mqc3_cloud.program.v1.CircuitRepresentation circuit = 2 [json_name = "circuit"];
inline bool QuantumProgram::has_circuit() const {
  return payload_case() == kCircuit;
}
inline bool QuantumProgram::_internal_has_circuit() const {
  return payload_case() == kCircuit;
}
inline void QuantumProgram::set_has_circuit() {
  _impl_._oneof_case_[0] = kCircuit;
}
inline ::mqc3_cloud::program::v1::CircuitRepresentation* QuantumProgram::release_circuit() {
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgram.circuit)
  if (payload_case() == kCircuit) {
    clear_has_payload();
    auto* temp = _impl_.payload_.circuit_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.circuit_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mqc3_cloud::program::v1::CircuitRepresentation& QuantumProgram::_internal_circuit() const {
  return payload_case() == kCircuit ? *_impl_.payload_.circuit_ : reinterpret_cast<::mqc3_cloud::program::v1::CircuitRepresentation&>(::mqc3_cloud::program::v1::_CircuitRepresentation_default_instance_);
}
inline const ::mqc3_cloud::program::v1::CircuitRepresentation& QuantumProgram::circuit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgram.circuit)
  return _internal_circuit();
}
inline ::mqc3_cloud::program::v1::CircuitRepresentation* QuantumProgram::unsafe_arena_release_circuit() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mqc3_cloud.program.v1.QuantumProgram.circuit)
  if (payload_case() == kCircuit) {
    clear_has_payload();
    auto* temp = _impl_.payload_.circuit_;
    _impl_.payload_.circuit_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void QuantumProgram::unsafe_arena_set_allocated_circuit(::mqc3_cloud::program::v1::CircuitRepresentation* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_circuit();
    _impl_.payload_.circuit_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgram.circuit)
}
inline ::mqc3_cloud::program::v1::CircuitRepresentation* QuantumProgram::_internal_mutable_circuit() {
  if (payload_case() != kCircuit) {
    clear_payload();
    set_has_circuit();
    _impl_.payload_.circuit_ =
        ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::CircuitRepresentation>(GetArena());
  }
  return _impl_.payload_.circuit_;
}
inline ::mqc3_cloud::program::v1::CircuitRepresentation* QuantumProgram::mutable_circuit() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::mqc3_cloud::program::v1::CircuitRepresentation* _msg = _internal_mutable_circuit();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgram.circuit)
  return _msg;
}

// .mqc3_cloud.program.v1.GraphRepresentation graph = 3 [json_name = "graph"];
inline bool QuantumProgram::has_graph() const {
  return payload_case() == kGraph;
}
inline bool QuantumProgram::_internal_has_graph() const {
  return payload_case() == kGraph;
}
inline void QuantumProgram::set_has_graph() {
  _impl_._oneof_case_[0] = kGraph;
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgram::release_graph() {
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgram.graph)
  if (payload_case() == kGraph) {
    clear_has_payload();
    auto* temp = _impl_.payload_.graph_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.graph_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mqc3_cloud::program::v1::GraphRepresentation& QuantumProgram::_internal_graph() const {
  return payload_case() == kGraph ? *_impl_.payload_.graph_ : reinterpret_cast<::mqc3_cloud::program::v1::GraphRepresentation&>(::mqc3_cloud::program::v1::_GraphRepresentation_default_instance_);
}
inline const ::mqc3_cloud::program::v1::GraphRepresentation& QuantumProgram::graph() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgram.graph)
  return _internal_graph();
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgram::unsafe_arena_release_graph() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mqc3_cloud.program.v1.QuantumProgram.graph)
  if (payload_case() == kGraph) {
    clear_has_payload();
    auto* temp = _impl_.payload_.graph_;
    _impl_.payload_.graph_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void QuantumProgram::unsafe_arena_set_allocated_graph(::mqc3_cloud::program::v1::GraphRepresentation* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_graph();
    _impl_.payload_.graph_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgram.graph)
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgram::_internal_mutable_graph() {
  if (payload_case() != kGraph) {
    clear_payload();
    set_has_graph();
    _impl_.payload_.graph_ =
        ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::GraphRepresentation>(GetArena());
  }
  return _impl_.payload_.graph_;
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgram::mutable_graph() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::mqc3_cloud::program::v1::GraphRepresentation* _msg = _internal_mutable_graph();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgram.graph)
  return _msg;
}

// .mqc3_cloud.program.v1.MachineryRepresentation machinery = 4 [json_name = "machinery"];
inline bool QuantumProgram::has_machinery() const {
  return payload_case() == kMachinery;
}
inline bool QuantumProgram::_internal_has_machinery() const {
  return payload_case() == kMachinery;
}
inline void QuantumProgram::set_has_machinery() {
  _impl_._oneof_case_[0] = kMachinery;
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgram::release_machinery() {
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgram.machinery)
  if (payload_case() == kMachinery) {
    clear_has_payload();
    auto* temp = _impl_.payload_.machinery_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.machinery_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mqc3_cloud::program::v1::MachineryRepresentation& QuantumProgram::_internal_machinery() const {
  return payload_case() == kMachinery ? *_impl_.payload_.machinery_ : reinterpret_cast<::mqc3_cloud::program::v1::MachineryRepresentation&>(::mqc3_cloud::program::v1::_MachineryRepresentation_default_instance_);
}
inline const ::mqc3_cloud::program::v1::MachineryRepresentation& QuantumProgram::machinery() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgram.machinery)
  return _internal_machinery();
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgram::unsafe_arena_release_machinery() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mqc3_cloud.program.v1.QuantumProgram.machinery)
  if (payload_case() == kMachinery) {
    clear_has_payload();
    auto* temp = _impl_.payload_.machinery_;
    _impl_.payload_.machinery_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void QuantumProgram::unsafe_arena_set_allocated_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_machinery();
    _impl_.payload_.machinery_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgram.machinery)
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgram::_internal_mutable_machinery() {
  if (payload_case() != kMachinery) {
    clear_payload();
    set_has_machinery();
    _impl_.payload_.machinery_ =
        ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::MachineryRepresentation>(GetArena());
  }
  return _impl_.payload_.machinery_;
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgram::mutable_machinery() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::mqc3_cloud::program::v1::MachineryRepresentation* _msg = _internal_mutable_machinery();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgram.machinery)
  return _msg;
}

inline bool QuantumProgram::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void QuantumProgram::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline QuantumProgram::PayloadCase QuantumProgram::payload_case() const {
  return QuantumProgram::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// QuantumProgramResult

// .mqc3_cloud.program.v1.CircuitResult circuit_result = 1 [json_name = "circuitResult"];
inline bool QuantumProgramResult::has_circuit_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.circuit_result_ != nullptr);
  return value;
}
inline const ::mqc3_cloud::program::v1::CircuitResult& QuantumProgramResult::_internal_circuit_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mqc3_cloud::program::v1::CircuitResult* p = _impl_.circuit_result_;
  return p != nullptr ? *p : reinterpret_cast<const ::mqc3_cloud::program::v1::CircuitResult&>(::mqc3_cloud::program::v1::_CircuitResult_default_instance_);
}
inline const ::mqc3_cloud::program::v1::CircuitResult& QuantumProgramResult::circuit_result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgramResult.circuit_result)
  return _internal_circuit_result();
}
inline void QuantumProgramResult::unsafe_arena_set_allocated_circuit_result(::mqc3_cloud::program::v1::CircuitResult* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.circuit_result_);
  }
  _impl_.circuit_result_ = reinterpret_cast<::mqc3_cloud::program::v1::CircuitResult*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.circuit_result)
}
inline ::mqc3_cloud::program::v1::CircuitResult* QuantumProgramResult::release_circuit_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mqc3_cloud::program::v1::CircuitResult* released = _impl_.circuit_result_;
  _impl_.circuit_result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::mqc3_cloud::program::v1::CircuitResult* QuantumProgramResult::unsafe_arena_release_circuit_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgramResult.circuit_result)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mqc3_cloud::program::v1::CircuitResult* temp = _impl_.circuit_result_;
  _impl_.circuit_result_ = nullptr;
  return temp;
}
inline ::mqc3_cloud::program::v1::CircuitResult* QuantumProgramResult::_internal_mutable_circuit_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.circuit_result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::CircuitResult>(GetArena());
    _impl_.circuit_result_ = reinterpret_cast<::mqc3_cloud::program::v1::CircuitResult*>(p);
  }
  return _impl_.circuit_result_;
}
inline ::mqc3_cloud::program::v1::CircuitResult* QuantumProgramResult::mutable_circuit_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::mqc3_cloud::program::v1::CircuitResult* _msg = _internal_mutable_circuit_result();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgramResult.circuit_result)
  return _msg;
}
inline void QuantumProgramResult::set_allocated_circuit_result(::mqc3_cloud::program::v1::CircuitResult* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.circuit_result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.circuit_result_ = reinterpret_cast<::mqc3_cloud::program::v1::CircuitResult*>(value);
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.circuit_result)
}

// .mqc3_cloud.program.v1.GraphResult graph_result = 2 [json_name = "graphResult"];
inline bool QuantumProgramResult::has_graph_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.graph_result_ != nullptr);
  return value;
}
inline const ::mqc3_cloud::program::v1::GraphResult& QuantumProgramResult::_internal_graph_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mqc3_cloud::program::v1::GraphResult* p = _impl_.graph_result_;
  return p != nullptr ? *p : reinterpret_cast<const ::mqc3_cloud::program::v1::GraphResult&>(::mqc3_cloud::program::v1::_GraphResult_default_instance_);
}
inline const ::mqc3_cloud::program::v1::GraphResult& QuantumProgramResult::graph_result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgramResult.graph_result)
  return _internal_graph_result();
}
inline void QuantumProgramResult::unsafe_arena_set_allocated_graph_result(::mqc3_cloud::program::v1::GraphResult* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.graph_result_);
  }
  _impl_.graph_result_ = reinterpret_cast<::mqc3_cloud::program::v1::GraphResult*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.graph_result)
}
inline ::mqc3_cloud::program::v1::GraphResult* QuantumProgramResult::release_graph_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mqc3_cloud::program::v1::GraphResult* released = _impl_.graph_result_;
  _impl_.graph_result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::mqc3_cloud::program::v1::GraphResult* QuantumProgramResult::unsafe_arena_release_graph_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgramResult.graph_result)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mqc3_cloud::program::v1::GraphResult* temp = _impl_.graph_result_;
  _impl_.graph_result_ = nullptr;
  return temp;
}
inline ::mqc3_cloud::program::v1::GraphResult* QuantumProgramResult::_internal_mutable_graph_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.graph_result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::GraphResult>(GetArena());
    _impl_.graph_result_ = reinterpret_cast<::mqc3_cloud::program::v1::GraphResult*>(p);
  }
  return _impl_.graph_result_;
}
inline ::mqc3_cloud::program::v1::GraphResult* QuantumProgramResult::mutable_graph_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::mqc3_cloud::program::v1::GraphResult* _msg = _internal_mutable_graph_result();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgramResult.graph_result)
  return _msg;
}
inline void QuantumProgramResult::set_allocated_graph_result(::mqc3_cloud::program::v1::GraphResult* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.graph_result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.graph_result_ = reinterpret_cast<::mqc3_cloud::program::v1::GraphResult*>(value);
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.graph_result)
}

// .mqc3_cloud.program.v1.MachineryResult machinery_result = 3 [json_name = "machineryResult"];
inline bool QuantumProgramResult::has_machinery_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.machinery_result_ != nullptr);
  return value;
}
inline const ::mqc3_cloud::program::v1::MachineryResult& QuantumProgramResult::_internal_machinery_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mqc3_cloud::program::v1::MachineryResult* p = _impl_.machinery_result_;
  return p != nullptr ? *p : reinterpret_cast<const ::mqc3_cloud::program::v1::MachineryResult&>(::mqc3_cloud::program::v1::_MachineryResult_default_instance_);
}
inline const ::mqc3_cloud::program::v1::MachineryResult& QuantumProgramResult::machinery_result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgramResult.machinery_result)
  return _internal_machinery_result();
}
inline void QuantumProgramResult::unsafe_arena_set_allocated_machinery_result(::mqc3_cloud::program::v1::MachineryResult* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.machinery_result_);
  }
  _impl_.machinery_result_ = reinterpret_cast<::mqc3_cloud::program::v1::MachineryResult*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.machinery_result)
}
inline ::mqc3_cloud::program::v1::MachineryResult* QuantumProgramResult::release_machinery_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::mqc3_cloud::program::v1::MachineryResult* released = _impl_.machinery_result_;
  _impl_.machinery_result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::mqc3_cloud::program::v1::MachineryResult* QuantumProgramResult::unsafe_arena_release_machinery_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgramResult.machinery_result)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::mqc3_cloud::program::v1::MachineryResult* temp = _impl_.machinery_result_;
  _impl_.machinery_result_ = nullptr;
  return temp;
}
inline ::mqc3_cloud::program::v1::MachineryResult* QuantumProgramResult::_internal_mutable_machinery_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.machinery_result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::MachineryResult>(GetArena());
    _impl_.machinery_result_ = reinterpret_cast<::mqc3_cloud::program::v1::MachineryResult*>(p);
  }
  return _impl_.machinery_result_;
}
inline ::mqc3_cloud::program::v1::MachineryResult* QuantumProgramResult::mutable_machinery_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::mqc3_cloud::program::v1::MachineryResult* _msg = _internal_mutable_machinery_result();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgramResult.machinery_result)
  return _msg;
}
inline void QuantumProgramResult::set_allocated_machinery_result(::mqc3_cloud::program::v1::MachineryResult* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.machinery_result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.machinery_result_ = reinterpret_cast<::mqc3_cloud::program::v1::MachineryResult*>(value);
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.machinery_result)
}

// .mqc3_cloud.program.v1.GraphRepresentation compiled_graph = 4 [json_name = "compiledGraph"];
inline bool QuantumProgramResult::has_compiled_graph() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.compiled_graph_ != nullptr);
  return value;
}
inline const ::mqc3_cloud::program::v1::GraphRepresentation& QuantumProgramResult::_internal_compiled_graph() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mqc3_cloud::program::v1::GraphRepresentation* p = _impl_.compiled_graph_;
  return p != nullptr ? *p : reinterpret_cast<const ::mqc3_cloud::program::v1::GraphRepresentation&>(::mqc3_cloud::program::v1::_GraphRepresentation_default_instance_);
}
inline const ::mqc3_cloud::program::v1::GraphRepresentation& QuantumProgramResult::compiled_graph() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgramResult.compiled_graph)
  return _internal_compiled_graph();
}
inline void QuantumProgramResult::unsafe_arena_set_allocated_compiled_graph(::mqc3_cloud::program::v1::GraphRepresentation* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.compiled_graph_);
  }
  _impl_.compiled_graph_ = reinterpret_cast<::mqc3_cloud::program::v1::GraphRepresentation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.compiled_graph)
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgramResult::release_compiled_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::mqc3_cloud::program::v1::GraphRepresentation* released = _impl_.compiled_graph_;
  _impl_.compiled_graph_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgramResult::unsafe_arena_release_compiled_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgramResult.compiled_graph)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::mqc3_cloud::program::v1::GraphRepresentation* temp = _impl_.compiled_graph_;
  _impl_.compiled_graph_ = nullptr;
  return temp;
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgramResult::_internal_mutable_compiled_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.compiled_graph_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::GraphRepresentation>(GetArena());
    _impl_.compiled_graph_ = reinterpret_cast<::mqc3_cloud::program::v1::GraphRepresentation*>(p);
  }
  return _impl_.compiled_graph_;
}
inline ::mqc3_cloud::program::v1::GraphRepresentation* QuantumProgramResult::mutable_compiled_graph() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::mqc3_cloud::program::v1::GraphRepresentation* _msg = _internal_mutable_compiled_graph();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgramResult.compiled_graph)
  return _msg;
}
inline void QuantumProgramResult::set_allocated_compiled_graph(::mqc3_cloud::program::v1::GraphRepresentation* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.compiled_graph_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.compiled_graph_ = reinterpret_cast<::mqc3_cloud::program::v1::GraphRepresentation*>(value);
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.compiled_graph)
}

// .mqc3_cloud.program.v1.MachineryRepresentation compiled_machinery = 5 [json_name = "compiledMachinery"];
inline bool QuantumProgramResult::has_compiled_machinery() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.compiled_machinery_ != nullptr);
  return value;
}
inline const ::mqc3_cloud::program::v1::MachineryRepresentation& QuantumProgramResult::_internal_compiled_machinery() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mqc3_cloud::program::v1::MachineryRepresentation* p = _impl_.compiled_machinery_;
  return p != nullptr ? *p : reinterpret_cast<const ::mqc3_cloud::program::v1::MachineryRepresentation&>(::mqc3_cloud::program::v1::_MachineryRepresentation_default_instance_);
}
inline const ::mqc3_cloud::program::v1::MachineryRepresentation& QuantumProgramResult::compiled_machinery() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgramResult.compiled_machinery)
  return _internal_compiled_machinery();
}
inline void QuantumProgramResult::unsafe_arena_set_allocated_compiled_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.compiled_machinery_);
  }
  _impl_.compiled_machinery_ = reinterpret_cast<::mqc3_cloud::program::v1::MachineryRepresentation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.compiled_machinery)
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgramResult::release_compiled_machinery() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::mqc3_cloud::program::v1::MachineryRepresentation* released = _impl_.compiled_machinery_;
  _impl_.compiled_machinery_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgramResult::unsafe_arena_release_compiled_machinery() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqc3_cloud.program.v1.QuantumProgramResult.compiled_machinery)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::mqc3_cloud::program::v1::MachineryRepresentation* temp = _impl_.compiled_machinery_;
  _impl_.compiled_machinery_ = nullptr;
  return temp;
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgramResult::_internal_mutable_compiled_machinery() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.compiled_machinery_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mqc3_cloud::program::v1::MachineryRepresentation>(GetArena());
    _impl_.compiled_machinery_ = reinterpret_cast<::mqc3_cloud::program::v1::MachineryRepresentation*>(p);
  }
  return _impl_.compiled_machinery_;
}
inline ::mqc3_cloud::program::v1::MachineryRepresentation* QuantumProgramResult::mutable_compiled_machinery() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::mqc3_cloud::program::v1::MachineryRepresentation* _msg = _internal_mutable_compiled_machinery();
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgramResult.compiled_machinery)
  return _msg;
}
inline void QuantumProgramResult::set_allocated_compiled_machinery(::mqc3_cloud::program::v1::MachineryRepresentation* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.compiled_machinery_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.compiled_machinery_ = reinterpret_cast<::mqc3_cloud::program::v1::MachineryRepresentation*>(value);
  // @@protoc_insertion_point(field_set_allocated:mqc3_cloud.program.v1.QuantumProgramResult.compiled_machinery)
}

// repeated .mqc3_cloud.program.v1.BosonicState circuit_state = 6 [json_name = "circuitState"];
inline int QuantumProgramResult::_internal_circuit_state_size() const {
  return _internal_circuit_state().size();
}
inline int QuantumProgramResult::circuit_state_size() const {
  return _internal_circuit_state_size();
}
inline ::mqc3_cloud::program::v1::BosonicState* QuantumProgramResult::mutable_circuit_state(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mqc3_cloud.program.v1.QuantumProgramResult.circuit_state)
  return _internal_mutable_circuit_state()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>* QuantumProgramResult::mutable_circuit_state()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:mqc3_cloud.program.v1.QuantumProgramResult.circuit_state)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_circuit_state();
}
inline const ::mqc3_cloud::program::v1::BosonicState& QuantumProgramResult::circuit_state(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqc3_cloud.program.v1.QuantumProgramResult.circuit_state)
  return _internal_circuit_state().Get(index);
}
inline ::mqc3_cloud::program::v1::BosonicState* QuantumProgramResult::add_circuit_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::mqc3_cloud::program::v1::BosonicState* _add = _internal_mutable_circuit_state()->Add();
  // @@protoc_insertion_point(field_add:mqc3_cloud.program.v1.QuantumProgramResult.circuit_state)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>& QuantumProgramResult::circuit_state() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mqc3_cloud.program.v1.QuantumProgramResult.circuit_state)
  return _internal_circuit_state();
}
inline const ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>&
QuantumProgramResult::_internal_circuit_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.circuit_state_;
}
inline ::google::protobuf::RepeatedPtrField<::mqc3_cloud::program::v1::BosonicState>*
QuantumProgramResult::_internal_mutable_circuit_state() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.circuit_state_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace program
}  // namespace mqc3_cloud


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mqc3_cloud::program::v1::RepresentationFormat> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::mqc3_cloud::program::v1::RepresentationFormat>() {
  return ::mqc3_cloud::program::v1::RepresentationFormat_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_mqc3_5fcloud_2fprogram_2fv1_2fquantum_5fprogram_2eproto_2epb_2eh
