// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mqc3_cloud/scheduler/v1/execution.proto
// Original file comments:
// MQC3 Execution Service API
//
// This protocol buffer defines the gRPC interface used by quantum computer
// controllers ("physical_labs") to interact with the MQC3 cloud job scheduler.
// It provides mechanisms for assigning queued jobs, reporting execution results,
// and requesting refreshed upload URLs when needed.
//
// This file is part of the MQC3 Scheduler Protocol Suite.
// See also: job.proto, submission.proto
//
#ifndef GRPC_mqc3_5fcloud_2fscheduler_2fv1_2fexecution_2eproto__INCLUDED
#define GRPC_mqc3_5fcloud_2fscheduler_2fv1_2fexecution_2eproto__INCLUDED

#include "mqc3_cloud/scheduler/v1/execution.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace mqc3_cloud {
namespace scheduler {
namespace v1 {

// ExecutionService defines the interface for a quantum computer to interact with
// the scheduling system. It enables job assignment, result reporting, and
// upload URL management. Intended for use by physical_lab (quantum computer controller).
class ExecutionService final {
 public:
  static constexpr char const* service_full_name() {
    return "mqc3_cloud.scheduler.v1.ExecutionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Assigns the next available job in the execution queue to the requesting backend.
    //
    // This RPC ensures that the assigned job is exclusively reserved for the requesting
    // controller and will not be assigned to any other backend. If no job is currently
    // queued, the response will contain an empty job_id.
    //
    // Use this method to periodically check for assignable jobs.
    virtual ::grpc::Status AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>> AsyncAssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>>(AsyncAssignNextJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>> PrepareAsyncAssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>>(PrepareAsyncAssignNextJobRaw(context, request, cq));
    }
    // Reports the final execution result and metadata of a previously assigned job.
    // Includes timestamps, backend identification, and uploaded result receipt/metrics.
    virtual ::grpc::Status ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>> AsyncReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>>(AsyncReportExecutionResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>> PrepareAsyncReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>>(PrepareAsyncReportExecutionResultRaw(context, request, cq));
    }
    // Requests a new upload URL for a previously assigned job.
    // This is typically used when the original URL has expired.
    virtual ::grpc::Status RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>> AsyncRefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>>(AsyncRefreshUploadUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>> PrepareAsyncRefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>>(PrepareAsyncRefreshUploadUrlRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Assigns the next available job in the execution queue to the requesting backend.
      //
      // This RPC ensures that the assigned job is exclusively reserved for the requesting
      // controller and will not be assigned to any other backend. If no job is currently
      // queued, the response will contain an empty job_id.
      //
      // Use this method to periodically check for assignable jobs.
      virtual void AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Reports the final execution result and metadata of a previously assigned job.
      // Includes timestamps, backend identification, and uploaded result receipt/metrics.
      virtual void ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Requests a new upload URL for a previously assigned job.
      // This is typically used when the original URL has expired.
      virtual void RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* AsyncAssignNextJobRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* PrepareAsyncAssignNextJobRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* AsyncReportExecutionResultRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* PrepareAsyncReportExecutionResultRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* AsyncRefreshUploadUrlRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* PrepareAsyncRefreshUploadUrlRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>> AsyncAssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>>(AsyncAssignNextJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>> PrepareAsyncAssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>>(PrepareAsyncAssignNextJobRaw(context, request, cq));
    }
    ::grpc::Status ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>> AsyncReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>>(AsyncReportExecutionResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>> PrepareAsyncReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>>(PrepareAsyncReportExecutionResultRaw(context, request, cq));
    }
    ::grpc::Status RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>> AsyncRefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>>(AsyncRefreshUploadUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>> PrepareAsyncRefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>>(PrepareAsyncRefreshUploadUrlRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response, std::function<void(::grpc::Status)>) override;
      void AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response, std::function<void(::grpc::Status)>) override;
      void RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* AsyncAssignNextJobRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* PrepareAsyncAssignNextJobRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* AsyncReportExecutionResultRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* PrepareAsyncReportExecutionResultRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* AsyncRefreshUploadUrlRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* PrepareAsyncRefreshUploadUrlRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AssignNextJob_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportExecutionResult_;
    const ::grpc::internal::RpcMethod rpcmethod_RefreshUploadUrl_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Assigns the next available job in the execution queue to the requesting backend.
    //
    // This RPC ensures that the assigned job is exclusively reserved for the requesting
    // controller and will not be assigned to any other backend. If no job is currently
    // queued, the response will contain an empty job_id.
    //
    // Use this method to periodically check for assignable jobs.
    virtual ::grpc::Status AssignNextJob(::grpc::ServerContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response);
    // Reports the final execution result and metadata of a previously assigned job.
    // Includes timestamps, backend identification, and uploaded result receipt/metrics.
    virtual ::grpc::Status ReportExecutionResult(::grpc::ServerContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response);
    // Requests a new upload URL for a previously assigned job.
    // This is typically used when the original URL has expired.
    virtual ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AssignNextJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AssignNextJob() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AssignNextJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignNextJob(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAssignNextJob(::grpc::ServerContext* context, ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportExecutionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportExecutionResult() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReportExecutionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportExecutionResult(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportExecutionResult(::grpc::ServerContext* context, ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::grpc::ServerAsyncResponseWriter< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RefreshUploadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RefreshUploadUrl() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RefreshUploadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRefreshUploadUrl(::grpc::ServerContext* context, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::grpc::ServerAsyncResponseWriter< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AssignNextJob<WithAsyncMethod_ReportExecutionResult<WithAsyncMethod_RefreshUploadUrl<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AssignNextJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AssignNextJob() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response) { return this->AssignNextJob(context, request, response); }));}
    void SetMessageAllocatorFor_AssignNextJob(
        ::grpc::MessageAllocator< ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AssignNextJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignNextJob(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AssignNextJob(
      ::grpc::CallbackServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportExecutionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportExecutionResult() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response) { return this->ReportExecutionResult(context, request, response); }));}
    void SetMessageAllocatorFor_ReportExecutionResult(
        ::grpc::MessageAllocator< ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportExecutionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportExecutionResult(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportExecutionResult(
      ::grpc::CallbackServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RefreshUploadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RefreshUploadUrl() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response) { return this->RefreshUploadUrl(context, request, response); }));}
    void SetMessageAllocatorFor_RefreshUploadUrl(
        ::grpc::MessageAllocator< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RefreshUploadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RefreshUploadUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AssignNextJob<WithCallbackMethod_ReportExecutionResult<WithCallbackMethod_RefreshUploadUrl<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AssignNextJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AssignNextJob() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AssignNextJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignNextJob(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportExecutionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportExecutionResult() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReportExecutionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportExecutionResult(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RefreshUploadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RefreshUploadUrl() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RefreshUploadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AssignNextJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AssignNextJob() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AssignNextJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignNextJob(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAssignNextJob(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportExecutionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportExecutionResult() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReportExecutionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportExecutionResult(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportExecutionResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RefreshUploadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RefreshUploadUrl() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RefreshUploadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRefreshUploadUrl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AssignNextJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AssignNextJob() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AssignNextJob(context, request, response); }));
    }
    ~WithRawCallbackMethod_AssignNextJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignNextJob(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AssignNextJob(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportExecutionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportExecutionResult() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportExecutionResult(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportExecutionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportExecutionResult(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportExecutionResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RefreshUploadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RefreshUploadUrl() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RefreshUploadUrl(context, request, response); }));
    }
    ~WithRawCallbackMethod_RefreshUploadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RefreshUploadUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AssignNextJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AssignNextJob() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* streamer) {
                       return this->StreamedAssignNextJob(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AssignNextJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AssignNextJob(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* /*request*/, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAssignNextJob(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mqc3_cloud::scheduler::v1::AssignNextJobRequest,::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportExecutionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportExecutionResult() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* streamer) {
                       return this->StreamedReportExecutionResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportExecutionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportExecutionResult(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* /*request*/, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportExecutionResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest,::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RefreshUploadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RefreshUploadUrl() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* streamer) {
                       return this->StreamedRefreshUploadUrl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RefreshUploadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RefreshUploadUrl(::grpc::ServerContext* /*context*/, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* /*request*/, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRefreshUploadUrl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest,::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AssignNextJob<WithStreamedUnaryMethod_ReportExecutionResult<WithStreamedUnaryMethod_RefreshUploadUrl<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AssignNextJob<WithStreamedUnaryMethod_ReportExecutionResult<WithStreamedUnaryMethod_RefreshUploadUrl<Service > > > StreamedService;
};

}  // namespace v1
}  // namespace scheduler
}  // namespace mqc3_cloud


#endif  // GRPC_mqc3_5fcloud_2fscheduler_2fv1_2fexecution_2eproto__INCLUDED
