// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mqc3_cloud/scheduler/v1/execution.proto

#include "mqc3_cloud/scheduler/v1/execution.pb.h"
#include "mqc3_cloud/scheduler/v1/execution.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mqc3_cloud {
namespace scheduler {
namespace v1 {

static const char* ExecutionService_method_names[] = {
  "/mqc3_cloud.scheduler.v1.ExecutionService/AssignNextJob",
  "/mqc3_cloud.scheduler.v1.ExecutionService/ReportExecutionResult",
  "/mqc3_cloud.scheduler.v1.ExecutionService/RefreshUploadUrl",
};

std::unique_ptr< ExecutionService::Stub> ExecutionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ExecutionService::Stub> stub(new ExecutionService::Stub(channel, options));
  return stub;
}

ExecutionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AssignNextJob_(ExecutionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportExecutionResult_(ExecutionService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RefreshUploadUrl_(ExecutionService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ExecutionService::Stub::AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AssignNextJob_, context, request, response);
}

void ExecutionService::Stub::async::AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssignNextJob_, context, request, response, std::move(f));
}

void ExecutionService::Stub::async::AssignNextJob(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssignNextJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* ExecutionService::Stub::PrepareAsyncAssignNextJobRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse, ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AssignNextJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::AssignNextJobResponse>* ExecutionService::Stub::AsyncAssignNextJobRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAssignNextJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ExecutionService::Stub::ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportExecutionResult_, context, request, response);
}

void ExecutionService::Stub::async::ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportExecutionResult_, context, request, response, std::move(f));
}

void ExecutionService::Stub::async::ReportExecutionResult(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportExecutionResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* ExecutionService::Stub::PrepareAsyncReportExecutionResultRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse, ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportExecutionResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse>* ExecutionService::Stub::AsyncReportExecutionResultRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportExecutionResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ExecutionService::Stub::RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RefreshUploadUrl_, context, request, response);
}

void ExecutionService::Stub::async::RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RefreshUploadUrl_, context, request, response, std::move(f));
}

void ExecutionService::Stub::async::RefreshUploadUrl(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RefreshUploadUrl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* ExecutionService::Stub::PrepareAsyncRefreshUploadUrlRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RefreshUploadUrl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse>* ExecutionService::Stub::AsyncRefreshUploadUrlRaw(::grpc::ClientContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRefreshUploadUrlRaw(context, request, cq);
  result->StartCall();
  return result;
}

ExecutionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExecutionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExecutionService::Service, ::mqc3_cloud::scheduler::v1::AssignNextJobRequest, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExecutionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* req,
             ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* resp) {
               return service->AssignNextJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExecutionService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExecutionService::Service, ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExecutionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* req,
             ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* resp) {
               return service->ReportExecutionResult(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExecutionService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExecutionService::Service, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExecutionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* req,
             ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* resp) {
               return service->RefreshUploadUrl(ctx, req, resp);
             }, this)));
}

ExecutionService::Service::~Service() {
}

::grpc::Status ExecutionService::Service::AssignNextJob(::grpc::ServerContext* context, const ::mqc3_cloud::scheduler::v1::AssignNextJobRequest* request, ::mqc3_cloud::scheduler::v1::AssignNextJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ExecutionService::Service::ReportExecutionResult(::grpc::ServerContext* context, const ::mqc3_cloud::scheduler::v1::ReportExecutionResultRequest* request, ::mqc3_cloud::scheduler::v1::ReportExecutionResultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ExecutionService::Service::RefreshUploadUrl(::grpc::ServerContext* context, const ::mqc3_cloud::scheduler::v1::RefreshUploadUrlRequest* request, ::mqc3_cloud::scheduler::v1::RefreshUploadUrlResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mqc3_cloud
}  // namespace scheduler
}  // namespace v1

