#pragma once

#define INVALID_PROGRAM "INVALID_PROGRAM"
#define EXECUTION_FAILED "EXECUTION_FAILED"
#define TIMEOUT "TIMEOUT"
#define INTERNAL_ERROR "INTERNAL_ERROR"
#define CRITICAL_ERROR "CRITICAL_ERROR"
